Repository Wanderers-Of-The-Rift/wotr-mod, pull requests merged in 2025-05, with the labels that each got.

#167 fix: (#160) added missing translation strings
  src/generated/resources/assets/wotr/lang/en_us.json
  src/main/java/com/wanderersoftherift/wotr/datagen/ModLanguageProvider.java
Labels: Bug Fix

#170 (#135) Move abilities out of data gen
  src/generated/resources/data/wotr/tags/wotr/abilities/rift_drops.json
  src/main/java/com/wanderersoftherift/wotr/abilities/AbstractAbility.java
  src/main/java/com/wanderersoftherift/wotr/codec/LaxRegistryCodec.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModAbilityProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModAbilityTagsProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModObjectiveRecipeProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModRecipeProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeRecipeProvider.java
  src/main/resources/data/wotr/wotr/abilities/dash.json
  src/main/resources/data/wotr/wotr/abilities/fireball.json
  src/main/resources/data/wotr/wotr/abilities/heal.json
  src/main/resources/data/wotr/wotr/abilities/icicles.json
Labels: Refactor

#171 fix: (#148) Prevent spectator use of abilities
  src/main/java/com/wanderersoftherift/wotr/client/AbilityClientEvents.java
  src/main/java/com/wanderersoftherift/wotr/gui/layer/AbilityBar.java
  src/main/java/com/wanderersoftherift/wotr/gui/layer/ManaBar.java
  src/main/java/com/wanderersoftherift/wotr/network/SelectAbilitySlotPayload.java
  src/main/java/com/wanderersoftherift/wotr/network/UseAbilityPayload.java
Labels: Bug Fix

#172 fix: (#154) Limit random selectable rift themes and objectives
  src/generated/resources/data/wotr/tags/wotr/objective/random_selectable.json
  src/generated/resources/data/wotr/tags/wotr/rift_theme/random_selectable.json
  src/main/java/com/wanderersoftherift/wotr/datagen/DataGenerators.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModObjectiveTagsProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModRiftThemeTagsProvider.java
  src/main/java/com/wanderersoftherift/wotr/init/ModTags.java
  src/main/java/com/wanderersoftherift/wotr/rift/objective/RiftObjectiveEvents.java
  src/main/java/com/wanderersoftherift/wotr/world/level/levelgen/theme/LevelRiftThemeData.java
Labels: Bug Fix

#218 fix: (#205) improve dash
  src/main/resources/data/wotr/wotr/abilities/dash.json
Labels: Bug Fix

#214 feat: updated ability bench model and texture
  src/main/java/com/wanderersoftherift/wotr/block/AbilityBenchBlock.java
  src/main/resources/assets/wotr/models/block/ability_bench.json
  src/main/resources/assets/wotr/textures/block/ability_bench.png
Labels: Art

#215 fix: (#201) Make trial spawner behave better when covered
  src/generated/resources/assets/wotr/blockstates/rift_mob_spawner.json
  src/generated/resources/assets/wotr/models/block/rift_mob_spawner_active.json
  src/generated/resources/assets/wotr/models/block/rift_mob_spawner_active_ominous.json
  src/generated/resources/assets/wotr/models/block/rift_mob_spawner_ejecting_reward.json
  src/generated/resources/assets/wotr/models/block/rift_mob_spawner_ejecting_reward_ominous.json
  src/generated/resources/assets/wotr/models/block/rift_mob_spawner_inactive_ominous.json
  src/main/java/com/wanderersoftherift/wotr/block/RiftMobSpawnerBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/RiftMobSpawnerBlockEntity.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/riftmobspawner/RiftMobSpawner.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/riftmobspawner/RiftMobSpawnerData.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/riftmobspawner/RiftMobSpawnerState.java
  src/main/java/com/wanderersoftherift/wotr/client/render/blockentity/RiftMobSpawnerBlockEntityRenderer.java
  src/main/java/com/wanderersoftherift/wotr/datagen/WotrModelProvider.java
  src/main/java/com/wanderersoftherift/wotr/init/worldgen/WotrProcessors.java
  src/main/java/com/wanderersoftherift/wotr/mixin/TrialSpawnerAccessor.java
  src/main/java/com/wanderersoftherift/wotr/mixin/TrialSpawnerBlockEntityAccessor.java
  src/main/java/com/wanderersoftherift/wotr/world/level/levelgen/processor/RiftMobSpawnerProcessor.java
  src/main/resources/data/wotr/worldgen/processor_list/poi_theme_default.json
  src/main/resources/wotr.mixins.json
Labels: Bug Fix

#186 Updating the Key Forge model
  src/main/java/com/wanderersoftherift/wotr/block/KeyForgeBlock.java
  src/main/resources/assets/wotr/models/block/key_forge.json
  src/main/resources/assets/wotr/textures/block/key_forge.png
Labels: Art

#222 fix: (#210) Persists Rune Anvil contents
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/RuneAnvilBlockEntity.java
Labels: Bug Fix
