Repository Wanderers-Of-The-Rift/wotr-mod, pull requests merged in 2025-04, with the labels that each got.

#83 Pat/spawnerprocessor
  src/main/java/com/wanderersoftherift/wotr/init/ModProcessors.java
  src/main/java/com/wanderersoftherift/wotr/mixin/TrialSpawnerAccessor.java
  src/main/java/com/wanderersoftherift/wotr/world/level/levelgen/processor/TrialSpawnerProcessor.java
  src/main/resources/data/wotr/trial_spawner/test.json
  src/main/resources/data/wotr/worldgen/processor_list/poi_theme_default.json
  src/main/resources/wotr.mixins.json
Labels: Feature Implementation

#80 Add Ditto Blocks
  src/generated/resources/assets/wotr/blockstates/ditto_block.json
  src/generated/resources/assets/wotr/blockstates/mob_trap_block.json
  src/generated/resources/assets/wotr/blockstates/player_trap_block.json
  src/generated/resources/assets/wotr/blockstates/spring_block.json
  src/generated/resources/assets/wotr/blockstates/trap_block.json
  src/generated/resources/assets/wotr/items/ditto_block.json
  src/generated/resources/assets/wotr/items/mob_trap_block.json
  src/generated/resources/assets/wotr/items/player_trap_block.json
  src/generated/resources/assets/wotr/items/spring_block.json
  src/generated/resources/assets/wotr/items/trap_block.json
  src/generated/resources/assets/wotr/lang/en_us.json
  src/generated/resources/assets/wotr/models/block/ditto_block.json
  src/generated/resources/assets/wotr/models/block/mob_trap_block/0.json
  src/generated/resources/assets/wotr/models/block/mob_trap_block/1.json
  src/generated/resources/assets/wotr/models/block/mob_trap_block/2.json
  src/generated/resources/assets/wotr/models/block/player_trap_block/0.json
  src/generated/resources/assets/wotr/models/block/player_trap_block/1.json
  src/generated/resources/assets/wotr/models/block/player_trap_block/2.json
  src/generated/resources/assets/wotr/models/block/spring_block.json
  src/generated/resources/assets/wotr/models/block/trap_block/0.json
  src/generated/resources/assets/wotr/models/block/trap_block/1.json
  src/generated/resources/assets/wotr/models/block/trap_block/2.json
  src/generated/resources/data/wotr/loot_table/blocks/ditto_block.json
  src/generated/resources/data/wotr/loot_table/blocks/mob_trap_block.json
  src/generated/resources/data/wotr/loot_table/blocks/player_trap_block.json
  src/generated/resources/data/wotr/loot_table/blocks/spring_block.json
  src/generated/resources/data/wotr/loot_table/blocks/trap_block.json
  src/main/java/com/wanderersoftherift/wotr/block/DittoBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/MobTrapBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/PlayerTrapBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/RiftChestEntityBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/SpringBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/TrapBlock.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/DittoBlockEntity.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/DittoBlockEntityRenderer.java
  src/main/java/com/wanderersoftherift/wotr/block/blockentity/RuneAnvilBlockEntity.java
  src/main/java/com/wanderersoftherift/wotr/client/render/RenderEvents.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModBlockLootTableProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModLanguageProvider.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModModelProvider.java
  src/main/java/com/wanderersoftherift/wotr/init/ModBlockEntities.java
  src/main/java/com/wanderersoftherift/wotr/init/ModBlocks.java
  src/main/java/com/wanderersoftherift/wotr/init/client/ClientRegistryEvents.java
  src/main/java/com/wanderersoftherift/wotr/item/tools/WotRTweaker.java
  src/main/resources/assets/wotr/textures/block/ditto_block.png
  src/main/resources/assets/wotr/textures/block/mob_trap_block/0.png
  src/main/resources/assets/wotr/textures/block/mob_trap_block/1.png
  src/main/resources/assets/wotr/textures/block/mob_trap_block/2.png
  src/main/resources/assets/wotr/textures/block/player_trap_block/0.png
  src/main/resources/assets/wotr/textures/block/player_trap_block/1.png
  src/main/resources/assets/wotr/textures/block/player_trap_block/2.png
  src/main/resources/assets/wotr/textures/block/spring_block.png
  src/main/resources/assets/wotr/textures/block/spring_block_bottom.png
  src/main/resources/assets/wotr/textures/block/spring_block_side.png
  src/main/resources/assets/wotr/textures/block/spring_block_top.png
  src/main/resources/assets/wotr/textures/block/trap_block/0.png
  src/main/resources/assets/wotr/textures/block/trap_block/1.png
  src/main/resources/assets/wotr/textures/block/trap_block/2.png
  src/main/resources/assets/wotr/textures/item/dd_tweaker.png
Labels: Feature Implementation

#89 feat: arachnophobia accessibilty option replaces spiders with turtles
  src/main/java/com/wanderersoftherift/wotr/client/render/entity/AltSpiderRenderer.java
  src/main/java/com/wanderersoftherift/wotr/init/client/ClientRegistryEvents.java
  src/main/java/com/wanderersoftherift/wotr/mixin/MixinSpider.java
  src/main/resources/assets/wotr/textures/entity/alt_cave_spider.png
  src/main/resources/assets/wotr/textures/entity/alt_spider.png
  src/main/resources/wotr.mixins.json
Labels: Accessibility

#99 fix: correct broken player attributes registration
  src/main/java/com/wanderersoftherift/wotr/abilities/effects/marker/EffectDisplayData.java
  src/main/java/com/wanderersoftherift/wotr/abilities/effects/marker/EffectMarkerEvents.java
  src/main/java/com/wanderersoftherift/wotr/client/render/entity/state/SimpleEffectProjectileRenderState.java
  src/main/java/com/wanderersoftherift/wotr/datagen/provider/AbilityProvider.java
  src/main/java/com/wanderersoftherift/wotr/gui/menu/slot/AbilitySlot.java
  src/main/java/com/wanderersoftherift/wotr/gui/menu/slot/EssenceInputSlot.java
  src/main/java/com/wanderersoftherift/wotr/gui/menu/slot/KeyOutputSlot.java
  src/main/java/com/wanderersoftherift/wotr/gui/menu/slot/SkillThreadSlot.java
  src/main/java/com/wanderersoftherift/wotr/init/ModAttributes.java
  src/main/java/com/wanderersoftherift/wotr/init/client/ModGuiLayers.java
  src/main/java/com/wanderersoftherift/wotr/init/client/ModScreens.java
  src/main/java/com/wanderersoftherift/wotr/item/SkillThread.java
  src/main/java/com/wanderersoftherift/wotr/item/handler/ChangeAwareItemHandler.java
  src/main/resources/data/wotr/damage_type/fire.json
  src/main/resources/data/wotr/damage_type/fire_burn.json
Labels: Bug Fix

#97 Inventory snapshot integration with rift entry
  src/generated/resources/assets/wotr/lang/en_us.json
  src/main/java/com/wanderersoftherift/wotr/WanderersOfTheRift.java
  src/main/java/com/wanderersoftherift/wotr/client/render/entity/RiftEntranceRenderer.java
  src/main/java/com/wanderersoftherift/wotr/client/render/entity/RiftPortalRenderer.java
  src/main/java/com/wanderersoftherift/wotr/commands/InventorySnapshotCommands.java
  src/main/java/com/wanderersoftherift/wotr/core/inventory/snapshot/InventorySnapshotEvents.java
  src/main/java/com/wanderersoftherift/wotr/core/inventory/snapshot/InventorySnapshotSystem.java
  src/main/java/com/wanderersoftherift/wotr/core/rift/RiftLevelManager.java
  src/main/java/com/wanderersoftherift/wotr/datagen/ModLanguageProvider.java
  src/main/java/com/wanderersoftherift/wotr/entity/portal/RiftPortalEntity.java
  src/main/java/com/wanderersoftherift/wotr/entity/portal/RiftPortalEntranceEntity.java
  src/main/java/com/wanderersoftherift/wotr/entity/portal/RiftPortalExitEntity.java
  src/main/java/com/wanderersoftherift/wotr/init/ModContainerTypes.java
  src/main/java/com/wanderersoftherift/wotr/init/RegistryEvents.java
  src/main/java/com/wanderersoftherift/wotr/init/client/ClientRegistryEvents.java
  src/main/java/com/wanderersoftherift/wotr/interop/sophisticatedbackpacks/SophisticatedBackpackInterop.java
Labels: Feature Implementation
